name: Shiny Cloudflared Tunnel

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger the workflow'
        required: true
        default: 'curl'

env:
  TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/seqyuan/shiny:1.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y jq

      - name: Install cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          dpkg -i cloudflared-linux-amd64.deb
          rm cloudflared-linux-amd64.deb

      - name: Start Shiny app
        run: |
          R -e "shiny::runApp('app.R', port = 8082, host = '0.0.0.0')" &
          sleep 5  # Wait for Shiny to start

      - name: Start tunnel and get URL
        id: tunnel
        run: |
          # Start tunnel in background
          cloudflared tunnel run --token $TUNNEL_TOKEN --url http://localhost:8082 &
          sleep 10  # Wait for tunnel to establish
          
          # Get tunnel ID from token
          TUNNEL_ID=$(echo $TUNNEL_TOKEN | base64 -d | jq -r '.t')
          echo "tunnel_id=$TUNNEL_ID" >> $GITHUB_OUTPUT
          
          # Get tunnel URL
          TUNNEL_URL=$(cloudflared tunnel info $TUNNEL_ID | grep -oP '(?<=url=)[^ ]+')
          echo "tunnel_url=$TUNNEL_URL" >> $GITHUB_OUTPUT
          
          # Display tunnel information
          echo "Tunnel ID: $TUNNEL_ID"
          echo "Tunnel URL: $TUNNEL_URL" 