name: Shiny Cloudflared Tunnel

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger the workflow'
        required: true
        default: 'curl'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/seqyuan/shiny:1.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          dpkg -i cloudflared-linux-amd64.deb
          rm cloudflared-linux-amd64.deb

      - name: Start Shiny app
        run: |
          R -e "shiny::runApp('app.R', port = 8082, host = '0.0.0.0')" &
          sleep 5  # Wait for Shiny to start

      - name: Start cloudflared tunnel
        run: |
          cloudflared tunnel --url http://localhost:8082 &
          sleep 5  # Wait for tunnel to establish
          echo "Cloudflared tunnel URL:"
          cloudflared tunnel info 