name: Shiny Cloudflared Tunnel

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Trigger for manual run'
        required: true
        default: 'manual'

env:
  TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
  TUNNEL_ID: "84f79e3b-5caf-49e5-abd5-4b9dcbc08133"
  TUNNEL_DOMAIN: "enrich.bodagene.cn"
  #TUNNEL_ORIGIN_CERT: ${{ secrets.TUNNEL_ORIGIN_CERT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/seqyuan/shiny:1.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y jq

      - name: Install cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          dpkg -i cloudflared-linux-amd64.deb
          rm cloudflared-linux-amd64.deb

      - name: Start Shiny app
        run: |
          R -e "shiny::runApp('app.R', port = 8082, host = '0.0.0.0')" &
          sleep 5  # Wait for Shiny to start

      - name: Start tunnel and get URL
        id: tunnel
        run: |
          # Start tunnel in background with token
          cloudflared tunnel run --token $TUNNEL_TOKEN --url http://localhost:8082 &
          sleep 10  # Wait for tunnel to establish
          
          # Use tunnel ID from environment variable
          echo "tunnel_id=$TUNNEL_ID" >> $GITHUB_OUTPUT
          
          # Use domain from environment variable
          TUNNEL_URL="https://$TUNNEL_DOMAIN"
          echo "tunnel_url=$TUNNEL_URL" >> $GITHUB_OUTPUT
          
          # Display tunnel information
          echo "Tunnel ID: $TUNNEL_ID"
          echo "Tunnel URL: $TUNNEL_URL"
          
          # Keep the workflow running
          tail -f /dev/null 